## Plugin configuration for the KBase UI
---
plugins:
    # A rare class of plugin which provides services.
    service:
        -
            types
        -
            userprofileservice
    # Plugins which come-with kbase-ui
    builtIn:
        -
            mainwindow
        -
            message
        -
            welcome
        -
            login
        -
            userprofile
        -
            datasearch
        -
            narrativemanager
        -
            narrativestore 
    external:       
        -
            name: viswidgets
            bower:
                name: kbase-ui-plugin-vis-widgets
                version: eapearson/kbase-ui-plugin-vis-widgets#master
            copy:
                path: src/plugin
        -
            name: typeview
            bower:
                name: kbase-ui-plugin-typeview
                version: eapearson/kbase-ui-plugin-typeview#master
            copy:
                path: src/plugin
        -
            name: dataview
            bower:
                name: kbase-ui-plugin-dataview
                version: eapearson/kbase-ui-plugin-dataview#master
            copy:
                path: src/plugin
        -
            name: dashboard
            bower:
                name: kbase-ui-plugin-dashboard
                version: eapearson/kbase-ui-plugin-dashboard#master
            copy:
                path: src/plugin             
        -
            name: serviceclients
            bower:
                name: kbase-service-clients-js
                version: eapearson/kbase-service-clients-js#master
            copy:
                path: dist/plugin
        -
            name: datawidgets
            bower:
                name: kbase-ui-plugin-datawidgets
                version: eapearson/kbase-ui-plugin-datawidgets#master
            # The link install method will create a soft link in the plugin
            # dir to source/path
            #link:
            #    source: ../kbase-ui-plugin-datawidgets
            copy:
                path: src/plugin