dist: trusty
sudo: false
language: node_js

# Note that travis-ci docs do not always reflect the current state of
# node_js support. E.g. at the moment the docs say 4.2 is the latest on the 4.X 
# branch, but it is actually 4.4
node_js:
  - "6.9"

# upcoming
# addons:
#     apt:
#         packages:
#             - nginx
#     sauce_connect: true

#cache:
#  directories:
#  - bower_components
#  - node_modules
branches:
    only:
        - master
        - develop

install:
    - make init
    - make build config=ci

# upcoming
# Sets up the nginx server for proxying
# before_script:
#     - tools/travis/deploy-travis.sh
#     - tools/travis/start-nginx.sh

script: make test-travis

# upcoming
# after_script:
#     - tools/travis/stop-nginx.sh
