sudo: false
language: node_js
node_js:
  - "0.12"
  - "iojs"
cache:
  directories:
  - bower_components
  - node_modules
branches:
  only:
    - develop
    - staging
    - master
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - make
script: grunt test-travis