version: '3.2'
services:
  kbase-ui:
    volumes:
      - type: bind
        source: ../kbase-ui-plugin-jgi-search/src/plugin
        target: /kb/deployment/services/kbase-ui/dist/modules/plugins/jgi-search
      - type: bind
        source: ../kbase-common-es6/src
        target: /kb/deployment/services/kbase-ui/dist/modules/kb_lib
      - type: bind
        source: ./src/plugins/mainwindow
        target: /kb/deployment/services/kbase-ui/dist/modules/plugins/mainwindow
