menus:
    authenticated:
        main: [narrative, jgi-search]
        developer: [data-search, reske-admin, staging-browser]
        help: [about, about-services, contact-kbase, help]
    unauthenticated:
        main: []
        developer: []
        help: [about, contact-kbase, help]
