menus:
    hamburger:
        main:
            -
                id: narrative
                auth: true
            -
                id: jgi-search
                auth: true
        developer:
            -
                id: simple-search
                auth: true           
            -
                id: reske-admin
                auth: true
            -
                id: staging-browser
                auth: true
        help:
            -
                id: about
                auth: false
            -
                id: about-services
                auth: true
            -
                id: contact-kbase
                auth: false
            -
                id: help
                auth: false
    sidebar:
        main:
            -
                id: dashboard
                auth: true
            -
                id: appcatalog
                auth: false
            -
                id: search
                auth: true
                allow: [alpha]
            -
                id: jobbrowser
                # The label can ovveride the label from the plugin here
                label: Jobs
                auth: true
                allow: [alpha]
            -
                id: account
                auth: true
            -
                id: feeds
                auth: true
                allow: [alpha]