menus:
    authenticated:
        main: [narrative, bulk-ui]
        developer: [reske-admin, jgi-search, staging-browser]
        help: [about, about-services, contact-kbase, help]
    unauthenticated:
        main: []
        developer: []
        help: [about, contact-kbase, help]
