version: '3.6'
networks:
  kbase-dev:
    external:
      name: kbase-dev
services:
  kbase-ui:
    build:
      context: ../
      args:
        - BUILD=${BUILD}
    # just use dev_build for the image tag so we can easily clean
    # up afterwards.
    image: kbase/kbase-ui:dev_build
    networks:
      - kbase-dev
    container_name: kbase-ui
    command:
      - '-env'
      - /kb/deployment/config/${DEPLOY_ENV}.ini
      - '-template'
      - /kb/deployment/templates/nginx.conf.tmpl:/etc/nginx/nginx.conf
      - '-template'
      - /kb/deployment/templates/config.json.tmpl:/kb/deployment/services/kbase-ui/dist/modules/deploy/config.json
      - bash 
      - /kb/deployment/scripts/start-server.bash
    # environment:
    #     - dynamic_service_proxies=UIService
  kbase-ui-proxy:
      build:
        context: ../tools/proxy
      # there is only one proxy image, for local development, so just all it :dev
      image: kbase/kbase-ui-proxy:dev
      depends_on: 
        - kbase-ui
      networks:
        - kbase-dev
      container_name: kbase-ui-proxy
      ports:
        - "80:80"
        - "443:443"
      dns: 8.8.8.8
      # note that this is really a docker env file and is relative to the docker-compose file
      env_file: ../tools/proxy/conf/${DEPLOY_ENV}.env
      # environment:
      #   - dynamic_service_proxies=UIService
        #   - local_narrative
      


