menus:
    authenticated:
        main: [narrative, bulk-ui]
        developer: [reske-admin, jgi-search, reske-search, reske-type-search, reske-narrative-search, tester, test_dynamic_table, paveldemo, sdkclientstest, databrowser, typebrowser, jobbrowser, shockbrowser]
        help: [about, about-services, contact-kbase, about-kbase, help]
    unauthenticated:
        main: []
        developer: []
        help: [contact-kbase, about-kbase, help]
