## Global Build Config
---
targets:
    ui: dev
    deploy: narrative-dev
build:
    dist: true
    temp: ../temp
vfs: false
bower:
    offline: false
debug: false
server:
    port: 8080
features:
    auth:
        selected: auth1
