menus:
    authenticated: 
        main: [narrative]
        developer: []
        help: [about, contact-kbase, help]
    unauthenticated: 
        main: []
        developer: []
        help: [about, contact-kbase, help]
