menus:
    hamburger:
        main:
            -
                id: narrative
                auth: true
        developer:
            # no developer menu in prod build.
        help:
            -
                id: about
                auth: false
            -
                id: contact-kbase
                auth: false
            -
                id: help
                auth: false
    sidebar:
        main:
            -
                id: dashboard
                auth: true
            -
                id: appcatalog
                auth: false
            -
                id: search
                auth: true
            -
                id: jobbrowser
                # The label can ovveride the label from the plugin here
                label: Jobs
                auth: true
            -
                id: account
                auth: true