menus:
    authenticated:
        main: [narrative, bulk-ui]
        developer: [reske-admin, jgi-search]
        help: [about, about-services, contact-kbase, about-kbase, help]
        # TODO: congigurable sidebar menu items
        # sidebar: [dashboard, catalog, account, reske-narrative-search]
    unauthenticated:
        main: []
        developer: []
        help: [contact-kbase, about-kbase, help]
        # TODO: congigurable sidebar menu items
        # sidebar: [catalog]
