menus:
    authenticated:
        main: [narrative, search, bulk-ui]
        developer: [tester, test_dynamic_table, paveldemo, sdkclientstest, databrowser, typebrowser, jobbrowser, shockbrowser]
        help: [about, about-services, contact-kbase, about-kbase, help]
    unauthenticated:
        main: [search]
        developer: []
        help: [contact-kbase, about-kbase, help]
