## Build Configuration
---
plugins:
    # Plugins which come-with kbase-ui
    # - components
    - mainwindow
    - welcome
    - narrativemanager
    - about
    - login
    # external:
    - name: typeview
      globalName: kbase-ui-plugin-typeview
      cwd: src/plugin
      version: kbase-ui-plugin-typeview#payoff
      source:
          bower: {}
    - name: dataview
      globalName: kbase-ui-plugin-dataview
      version: kbase-ui-plugin-dataview#payoff
      cwd: src/plugin
      source:
        bower: {}
    - name: dashboard
      globalName: kbase-ui-plugin-dashboard
      version: kbase-ui-plugin-dashboard#payoff
      cwd: src/plugin
      source:
          bower: {}
    - name: job-browser2
      globalName: kbase-ui-plugin-job-browser2
      version: kbase-ui-plugin-job-browser2#payoff
      cwd: src/plugin
      source:
          git: 
            url: https://github.com/eapearson/kbase-ui-plugin-job-browser2
    - name: auth2-client
      globalName: kbase-ui-plugin-auth2-client
      version: kbase-ui-plugin-auth2-client#payoff
      cwd: src/plugin
      source:
          bower: {}
    - name: jgi-search
      globalName: kbase-ui-plugin-jgi-search
      version: kbase-ui-plugin-jgi-search#payoff
      cwd: src/plugin
      source:
          bower: {}
    - name: feeds
      globalName: kbase-ui-plugin-feeds
      version: kbase-ui-plugin-feeds#payoff
      cwd: src/plugin
      source:
        bower: {}
    - name: catalog
      globalName: kbase-ui-plugin-catalog
      version: kbase-ui-plugin-catalog#payoff
      cwd: src/plugin
      source:
          bower: {}
    - name: data-search
      globalName: kbase-ui-plugin-data-search
      version: kbase-ui-plugin-data-search#payoff
      cwd: src/plugin
      source:
        bower: {}
    - name: organizations
      globalName: kbase-ui-plugin-organizations
      version: kbase-ui-plugin-organizations#payoff
      cwd: src/plugin
      source:
        bower: {}
    - name: biochem-search
      globalName: kbase-ui-plugin-biochem-search
      version: kbase-ui-plugin-biochem-search#payoff
      cwd: src/plugin
      source:
        bower: {}
    - name: user-profile
      globalName: kbase-ui-plugin-user-profile
      version: kbase-ui-plugin-user-profile#payoff
      cwd: src/plugin
      source:
        bower: {}
    - name: example-hello
      globalName: kbase-ui-plugin-example-hello
      version: kbase-ui-plugin-example-hello#master
      cwd: plugin
      source:
          git: 
            url: https://github.com/eapearson/kbase-ui-plugin-example-hello
    
    # - name: narrative-info
    #   globalName: kbase-ui-plugin-narrative-info
    #   version: 1.1.4
    #   cwd: src/plugin
    #   source:
    #     bower: {}
    # - name: datawidgets
    #   globalName: kbase-ui-plugin-datawidgets
    #   version: 0.4.2
    #   cwd: src/plugin
    #   source:
    #     bower: {}
    # - name: data-landing-pages
    #   globalName: kbase-ui-plugin-data-landing-pages
    #   version: 0.8.0
    #   cwd: src/plugin
    #   source:
    #     bower: {}


    # Unreleased
    # - name: public-search
    #   globalName: kbase-ui-plugin-public-search
    #   version: 0.13.6
    #   cwd: src/plugin
    #   source:
    #     bower: {}

    # Experimental or Dev Only
    # - name: shockbrowser
    #   globalName: kbase-ui-plugin-shockbrowser
    #   version: 0.2.0
    #   cwd: src/plugin
    #   source:
    #     bower: {}
    # - name: staging-browser
    #   globalName: kbase-ui-plugin-staging-browser
    #   version: 0.1.2
    #   cwd: src/plugin
    #   source:
    #     bower: {}
    # - name: ui-service
    #   globalName: kbase-ui-plugin-ui-service
    #   version: 0.5.0
    #   cwd: src/plugin
    #   source:
    #     bower: {}
    # - name: dashboard2
    #   globalName: kbase-ui-plugin-dashboard2
    #   version: 0.2.2
    #   cwd: src/plugin
    #   source:
    #     bower: {}
    # - name: narrative-finder
    #   globalName: kbase-ui-plugin-narrative-finder
    #   version: 0.1.2
    #   cwd: src/plugin
    #   source:
    #     bower: {}

    # Obsolete
    # - name: methodview
    #   globalName: kbase-ui-plugin-methodview
    #   version: 1.1.0
    #   cwd: src/plugin
    #   source:
    #     bower: {}
    # - name: ontology-widgets
    #   globalName: kbase-ui-plugin-ontology-widgets
    #   version: 1.0.4
    #   cwd: src/plugin
    #   source:
    #     bower: {}