## YAML Template.
---
plugins:
    -
        -
            userprofileservice
        -
            types            
    -
        -
            serviceClients
        -
            mainwindow
        -
            message
        -
            welcome
        -
            login
        -
            dataview
        -
            typeview
        -
            dashboard
        -
            userprofile
        -
            datasearch
        -
            narrativemanager
        -
            narrativestore
        -
            viswidgets
menu:
    available_items:
    menus:
        authenticated: 
            main: [narrative, search, dashboard]
            help: [about-kbase, contact-kbase]
        unauthenticated: 
            main: [search]
            help: [about-kbase, contact-kbase]
