## UI Configuration File - Test
---
plugins:
    # NB: at the moment, but hopefully to be disentagled within a few days,
    # the plugins need to be loaded in this sequence of top level sections.
    # THis is because there are dependencies from later plugins to these.
    # Esp. type, which introduces a service for plugins (registering types)
    -
        -
            types
        -
            userprofileservice
    -
        -
            mainwindow
        -
            message
        -
            welcome
        -
            login
        #-
        #    serviceclients
        -
            name: serviceClients
            directory: bower_components/kbase-service-clients-js
    -
        #-
        #    name: dataview
        #    directory: ../../../kbase-ui-plugin-dataview/src/plugin
        -
            name: dataview
            directory: bower_components/kbase-ui-plugin-dataview
        #-
        #    dataview
        -
            name: typebrowser
            directory: bower_components/kbase-ui-plugin-typebrowser
        -
            name: typeview
            directory: bower_components/kbase-ui-plugin-typeview
        -
            name: dashboard
            directory: bower_components/kbase-ui-plugin-dashboard
        -
            userprofile
        -
            datasearch
        -
            narrativemanager
        -
            narrativestore            
        -
            name: viswidgets
            directory: bower_components/kbase-ui-plugin-vis-widgets
        #-
        #    databrowser
        -
            name: databrowser
            directory: bower_components/kbase-ui-plugin-databrowser        
menu:
    available_items:
#            search: 
#                path: search/?q=*
#                label: Search Data
#                icon: search
#            narrative: 
#                uri: "#narrativemanager/start"
#                label: Narrative
#                icon: file
#            narrativeTutorial: 
#                uri: https://kbase.us/narrative-guide
#                label: Narrative Tutorial
#                icon: info-circle
#
#            about_kbase: 
#                uri: https://kbase.us/about
#                label: About KBase
#                icon: info-circle
#            contact_kbase: 
#                uri: https://kbase.us/contact-us
#                label: Contact KBase
#                icon: envelope-o
#            dashboard:
#                uri: "#dashboard"
#                label: Dashboard
#                icon: dashboard
    menus:
        authenticated: 
            main: [narrative, search, dashboard]
            developer: [databrowser, typebrowser]
            help: [about-kbase, contact-kbase]
        unauthenticated: 
            main: [search]
            developer: []
            help: [about-kbase, contact-kbase]
