## UI Configuration File - Test
---
plugins:
    # NB: at the moment, but hopefully to be disentagled within a few days,
    # the plugins need to be loaded in this sequence of top level sections.
    # THis is because there are dependencies from later plugins to these.
    # Esp. type, which introduces a service for plugins (registering types)
    -
        -
            types
        -
            userprofileservice
    -
        -
            mainwindow
        -
            message
        -
            welcome
        -
            login
        -
            serviceclients
        -
            dataview
        -
            typebrowser
        -
            typeview
        -
            dashboard
        -
            userprofile
        -
            datasearch
        -
            narrativemanager
        -
            narrativestore            
        -
            viswidgets
        -
            databrowser
        -
            datawidgets
        -
            viswidgetdemo
menu:
    menus:
        authenticated: 
            main: [narrative, search, dashboard]
            developer: [databrowser, typebrowser, test, visdemoBarchart, visdemoHeatmap, visdemoLinechart, visdemoScatterplot]
            help: [about-kbase, contact-kbase]
        unauthenticated: 
            main: [search]
            developer: []
            help: [about-kbase, contact-kbase]