## Build Configuration
---
plugins:
    # Plugins which come-with kbase-ui
    -
        mainwindow
    -
        message
    -
        welcome
    -
        login
    -
        userprofile
    -
        datasearch
    -
        narrativemanager
    -
        narrativestore
    # external:
    -
        # Becomes the plugin directory name
        name: viswidgetdemo
        # Installation configuration.
        # Provided to bower. The package is fed to
        # bower install <package>
        # and
        # bower update <package>
        bower:
            name: kbase-ui-plugin-demo-vis-widget
            version: 0.1.1
        # This defaults to dist/plugin. If this is not the case, then
        # set it here. This is for the grunt task which copies the
        # package, as installed by bower.
        # The grunt "bowerCopy" tasks needs the bower package name, in order to locate
        # the source, the plugin name, to create the destination in plugins,
        # and the path within the packge to the plugin source, which is
        # standardized to dist/plugin but can be overridden by the cwd (named
        # to match the grunt usage of cwd to indicate the base directory for
        # a task operation on files.)
        copy:
            # only required if the code is not located in dist/plugin
            path: src/plugin
    -
        name: viswidgets
        bower:
            name: kbase-ui-plugin-vis-widgets
            version: 0.1.1
        copy:
            path: src/plugin
    -
        name: typeview
        bower:
            name: kbase-ui-plugin-typeview
            version: 0.1.1
        #link:
        #    source: ../kbase-ui-plugin-typeview
        copy:
            path: src/plugin
    -
        name: dataview
        bower:
            name: kbase-ui-plugin-dataview
            version: 0.1.2
        copy:
            path: src/plugin
    -
        name: dashboard
        bower:
            name: kbase-ui-plugin-dashboard
            version: 0.1.1
        copy:
            path: src/plugin
    -
        name: databrowser
        bower:
            name: kbase-ui-plugin-databrowser
            version: 0.1.1
        copy:
            path: src/plugin
    -
        name: typebrowser
        bower:
            name: kbase-ui-plugin-typebrowser
            version: 0.1.2
        copy:
            path: src/plugin
    -
        name: datawidgets
        bower:
             name: kbase-ui-plugin-datawidgets
             version: 0.1.3
        copy:
            path: src/plugin
               
# Copy these directories into the modules
# There are two forms, as for plugins. 
# a bower: section will specify a bower dependency
# a copy: section will specify a directory to copy literally into modules
# a link: section will specify a directory to link into modules

modules:
    -
        name: kbase-ui-widget
        bower:
            version: 0.1.4
    -
        name: kbase-common-js
        bower:
            version: 0.1.3
    -
        name: kbase-service-clients-js
        bower:
            version: 0.1.3
