menus:
    authenticated: 
        main: [narrative, search]
        developer: []
        help: [contact-kbase, about-kbase, help]
    unauthenticated: 
        main: [search]
        developer: []
        help: [contact-kbase, about-kbase, help]
