menus:
    authenticated: 
        main: [narrative, bulk-ui]
        developer: []
        help: [about, contact-kbase, about-kbase, help]
    unauthenticated: 
        main: []
        developer: []
        help: [about, contact-kbase, about-kbase, help]
