deploy:
    id: kbase-ui
    target: /kb/deployment/services/kbase-ui
    environment:
    hostname:
    icon:
    name:
# Settings in support of the user interface
ui:
    images:
        spinner:
            url: /images/ajax-loader.gif
    constants:
        client_timeout: 900000
        # session_max_age: 5184000
        # service check is conducted at ui startup; all core services are contacted to fetch
        # the current version. This affects the startup experience so we need to use a gradation
        # of timeouts. the slow timeout will trigger a warning for the user, but the check will
        # continue, the hard timeout will cancel the requests. slow is 10 seconds, hard limit is 1 minute.
        service_check_timeouts: 
            slow: 10000
            hard: 60000
     # TODO: simply paths?
    paths:
        spa_root: '#'
        landing_pages: '#dataview/'
        # ws_browser: '#/ws'
        version_check: /narrative_version
        dashboard_metrics: /userMetrics
    # TODO: simply urls?
    urls:
        reset_password: https://gologin.kbase.us/ResetPassword
        status_page: http://kbase.us/internal/status
        submit_jira_ticket: https://atlassian.kbase.us/secure/CreateIssueDetails!init.jspa?pid=10200&issuetype=1&description=#Narrative%20version
        update_profile: https://gologin.kbase.us/account/UpdateProfile
    # backupCookie:
    #   domain: null
    #   enabled: false
    # Services are configured here...
    services:
        analytics:
            cookie:
                name: kbase_client_id
                # approx 2 years
                maxAge: 63072000
            google:
                hostname: null
                code: null
        session:
            cookie:
                maxAge: 5184000
                name: kbase_session
                backup:
                    name: kbase_session_backup
                    domain: null
                    enabled: false
            # The widget id of the current login widget; supplied by the
            # auth plugin.
            loginWidget: auth2_signin

        route:
            defaultRoute:
                redirect:
                    path: login
        heartbeat:
            interval: 500
        # dynamic-service:
        #     hardTtl: 3600000 # 1 min
        #     hotTtl:  18000000 # 5 min
# Primarily for output links for the docsite.
# TODO: merge with ui.outbound_links?
docsite:
    base_url: http://kbase.us
    host: kbase.us
    paths:
        about: /what-is-kbase
        contact: /contact-us
        browser_support: /supported-browsers
